Repository alpaka-group/mallocMC, pull requests merged in 2020-05, with the labels that each got.

#170 Travis CI: GCC 5.5.0 + CUDA 9.1.85
  .travis.yml
Labels: example/test

#169 Cleaning & C++14 Migration
  CMakeLists.txt
  Usage.md
  examples/mallocMC_example01_config.cu
  examples/mallocMC_example02.cu
  examples/mallocMC_example03.cu
  src/include/mallocMC/alignmentPolicies/Noop_impl.hpp
  src/include/mallocMC/alignmentPolicies/Shrink.hpp
  src/include/mallocMC/alignmentPolicies/Shrink_impl.hpp
  src/include/mallocMC/allocator.hpp
  src/include/mallocMC/creationPolicies/OldMalloc_impl.hpp
  src/include/mallocMC/creationPolicies/Scatter.hpp
  src/include/mallocMC/creationPolicies/Scatter_impl.hpp
  src/include/mallocMC/device_allocator.hpp
  src/include/mallocMC/distributionPolicies/Noop.hpp
  src/include/mallocMC/distributionPolicies/Noop_impl.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp
  src/include/mallocMC/mallocMC_constraints.hpp
  src/include/mallocMC/mallocMC_traits.hpp
  src/include/mallocMC/mallocMC_utils.hpp
  src/include/mallocMC/oOMPolicies/BadAllocException_impl.hpp
  src/include/mallocMC/oOMPolicies/ReturnNull.hpp
  src/include/mallocMC/oOMPolicies/ReturnNull_impl.hpp
  src/include/mallocMC/reservePoolPolicies/CudaSetLimits_impl.hpp
  src/include/mallocMC/reservePoolPolicies/SimpleCudaMalloc_impl.hpp
  tests/verify_heap.cu
  tests/verify_heap_config.hpp
Labels: refactoring

#171 Adding headers to projects and applied clang-tidy
  .clang-tidy
  .gitignore
  CMakeLists.txt
  examples/mallocMC_example01.cu
  examples/mallocMC_example01_config.hpp
  examples/mallocMC_example02.cu
  examples/mallocMC_example03.cu
  src/include/mallocMC/alignmentPolicies/Noop_impl.hpp
  src/include/mallocMC/alignmentPolicies/Shrink.hpp
  src/include/mallocMC/alignmentPolicies/Shrink_impl.hpp
  src/include/mallocMC/allocator.hpp
  src/include/mallocMC/creationPolicies/OldMalloc_impl.hpp
  src/include/mallocMC/creationPolicies/Scatter.hpp
  src/include/mallocMC/creationPolicies/Scatter_impl.hpp
  src/include/mallocMC/device_allocator.hpp
  src/include/mallocMC/distributionPolicies/Noop_impl.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp
  src/include/mallocMC/mallocMC.hpp
  src/include/mallocMC/mallocMC_allocator_handle.hpp
  src/include/mallocMC/mallocMC_hostclass.hpp
  src/include/mallocMC/mallocMC_prefixes.hpp
  src/include/mallocMC/mallocMC_utils.hpp
  src/include/mallocMC/oOMPolicies/BadAllocException_impl.hpp
  src/include/mallocMC/oOMPolicies/ReturnNull_impl.hpp
  tests/verify_heap.cu
  tests/verify_heap_config.hpp
Labels: refactoring

#172 clang-format
  .clang-format
  .clang-tidy
  CONTRIBUTING.md
  README.md
  examples/mallocMC_example01.cu
  examples/mallocMC_example01_config.hpp
  examples/mallocMC_example02.cu
  examples/mallocMC_example03.cu
  src/include/mallocMC/AlignmentPolicies.hpp
  src/include/mallocMC/CreationPolicies.hpp
  src/include/mallocMC/DistributionPolicies.hpp
  src/include/mallocMC/OOMPolicies.hpp
  src/include/mallocMC/ReservePoolPolicies.hpp
  src/include/mallocMC/alignmentPolicies/Noop.hpp
  src/include/mallocMC/alignmentPolicies/Noop_impl.hpp
  src/include/mallocMC/alignmentPolicies/Shrink.hpp
  src/include/mallocMC/alignmentPolicies/Shrink_impl.hpp
  src/include/mallocMC/allocator.hpp
  src/include/mallocMC/creationPolicies/OldMalloc.hpp
  src/include/mallocMC/creationPolicies/OldMalloc_impl.hpp
  src/include/mallocMC/creationPolicies/Scatter.hpp
  src/include/mallocMC/creationPolicies/Scatter_impl.hpp
  src/include/mallocMC/device_allocator.hpp
  src/include/mallocMC/distributionPolicies/Noop.hpp
  src/include/mallocMC/distributionPolicies/Noop_impl.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp
  src/include/mallocMC/mallocMC_allocator_handle.hpp
  src/include/mallocMC/mallocMC_constraints.hpp
  src/include/mallocMC/mallocMC_prefixes.hpp
  src/include/mallocMC/mallocMC_traits.hpp
  src/include/mallocMC/mallocMC_utils.hpp
  src/include/mallocMC/oOMPolicies/BadAllocException.hpp
  src/include/mallocMC/oOMPolicies/BadAllocException_impl.hpp
  src/include/mallocMC/oOMPolicies/ReturnNull.hpp
  src/include/mallocMC/oOMPolicies/ReturnNull_impl.hpp
  src/include/mallocMC/reservePoolPolicies/CudaSetLimits.hpp
  src/include/mallocMC/reservePoolPolicies/CudaSetLimits_impl.hpp
  src/include/mallocMC/reservePoolPolicies/SimpleCudaMalloc.hpp
  src/include/mallocMC/reservePoolPolicies/SimpleCudaMalloc_impl.hpp
  tests/verify_heap.cu
  tests/verify_heap_config.hpp
Labels: refactoring

#174 update cmake to 3.15.0
  .travis.yml
Labels: example/test

#178 fix preferred cmake installation
  .travis.yml
Labels: bug, example/test

#179 Added 3rd party catch.hpp and made CMake find it
  CMakeLists.txt
  thirdParty/catch2/include/catch2/catch.hpp
Labels: example/test

#175 version update 2.4.0crp and changelog
  CHANGELOG.md
  src/include/mallocMC/version.hpp
Labels: documentation

#180 Release 2.4.0crp
  .clang-format
  .clang-tidy
  .gitignore
  .travis.yml
  CHANGELOG.md
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  Usage.md
  examples/mallocMC_example01.cu
  examples/mallocMC_example01_config.hpp
  examples/mallocMC_example02.cu
  examples/mallocMC_example03.cu
  src/include/mallocMC/AlignmentPolicies.hpp
  src/include/mallocMC/CreationPolicies.hpp
  src/include/mallocMC/DistributionPolicies.hpp
  src/include/mallocMC/OOMPolicies.hpp
  src/include/mallocMC/ReservePoolPolicies.hpp
  src/include/mallocMC/alignmentPolicies/Noop.hpp
  src/include/mallocMC/alignmentPolicies/Noop_impl.hpp
  src/include/mallocMC/alignmentPolicies/Shrink.hpp
  src/include/mallocMC/alignmentPolicies/Shrink_impl.hpp
  src/include/mallocMC/allocator.hpp
  src/include/mallocMC/creationPolicies/OldMalloc.hpp
  src/include/mallocMC/creationPolicies/OldMalloc_impl.hpp
  src/include/mallocMC/creationPolicies/Scatter.hpp
  src/include/mallocMC/creationPolicies/Scatter_impl.hpp
  src/include/mallocMC/device_allocator.hpp
  src/include/mallocMC/distributionPolicies/Noop.hpp
  src/include/mallocMC/distributionPolicies/Noop_impl.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp
  src/include/mallocMC/mallocMC.hpp
  src/include/mallocMC/mallocMC_allocator_handle.hpp
  src/include/mallocMC/mallocMC_constraints.hpp
  src/include/mallocMC/mallocMC_hostclass.hpp
  src/include/mallocMC/mallocMC_prefixes.hpp
  src/include/mallocMC/mallocMC_traits.hpp
  src/include/mallocMC/mallocMC_utils.hpp
  src/include/mallocMC/oOMPolicies/BadAllocException.hpp
  src/include/mallocMC/oOMPolicies/BadAllocException_impl.hpp
  src/include/mallocMC/oOMPolicies/ReturnNull.hpp
  src/include/mallocMC/oOMPolicies/ReturnNull_impl.hpp
  src/include/mallocMC/reservePoolPolicies/CudaSetLimits.hpp
  src/include/mallocMC/reservePoolPolicies/CudaSetLimits_impl.hpp
  src/include/mallocMC/reservePoolPolicies/SimpleCudaMalloc.hpp
  src/include/mallocMC/reservePoolPolicies/SimpleCudaMalloc_impl.hpp
  src/include/mallocMC/version.hpp
  tests/verify_heap.cu
  tests/verify_heap_config.hpp
Labels: documentation
