Repository alpaka-group/mallocMC, pull requests merged in 2020-07, with the labels that each got.

#182 fix HIP support
  src/include/mallocMC/creationPolicies/Scatter_impl.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp
  src/include/mallocMC/mallocMC_utils.hpp
  src/include/mallocMC/oOMPolicies/BadAllocException_impl.hpp
Labels: bug

#186 update version to 2.5.0-crp-dev
  src/include/mallocMC/version.hpp
Labels: documentation

#187 update gitignore
  .gitignore
Labels: feature

#181 Refactoring
  examples/mallocMC_example01.cpp
  examples/mallocMC_example03.cpp
  src/include/mallocMC/AlignmentPolicies.hpp
  src/include/mallocMC/CreationPolicies.hpp
  src/include/mallocMC/DistributionPolicies.hpp
  src/include/mallocMC/OOMPolicies.hpp
  src/include/mallocMC/ReservePoolPolicies.hpp
  src/include/mallocMC/alignmentPolicies/Noop.hpp
  src/include/mallocMC/alignmentPolicies/Noop_impl.hpp
  src/include/mallocMC/alignmentPolicies/Shrink.hpp
  src/include/mallocMC/alignmentPolicies/Shrink_impl.hpp
  src/include/mallocMC/creationPolicies/OldMalloc.hpp
  src/include/mallocMC/creationPolicies/OldMalloc_impl.hpp
  src/include/mallocMC/creationPolicies/Scatter.hpp
  src/include/mallocMC/creationPolicies/Scatter_impl.hpp
  src/include/mallocMC/distributionPolicies/Noop.hpp
  src/include/mallocMC/distributionPolicies/Noop_impl.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp
  src/include/mallocMC/mallocMC.hpp
  src/include/mallocMC/mallocMC_utils.hpp
  src/include/mallocMC/oOMPolicies/BadAllocException.hpp
  src/include/mallocMC/oOMPolicies/BadAllocException_impl.hpp
  src/include/mallocMC/oOMPolicies/ReturnNull.hpp
  src/include/mallocMC/oOMPolicies/ReturnNull_impl.hpp
  src/include/mallocMC/reservePoolPolicies/CudaSetLimits.hpp
  src/include/mallocMC/reservePoolPolicies/CudaSetLimits_impl.hpp
  tests/dimensions.cpp
  tests/policies.cpp
  tests/verify_heap_config.hpp
Labels: refactoring

#188 update alpaka subtree
  alpaka/.github/workflows/ci.yml
  alpaka/cmake/alpakaCommon.cmake
  alpaka/include/alpaka/acc/AccCpuFibers.hpp
  alpaka/include/alpaka/acc/AccCpuOmp2Blocks.hpp
  alpaka/include/alpaka/acc/AccCpuOmp2Threads.hpp
  alpaka/include/alpaka/acc/AccCpuOmp4.hpp
  alpaka/include/alpaka/acc/AccCpuSerial.hpp
  alpaka/include/alpaka/acc/AccCpuTbbBlocks.hpp
  alpaka/include/alpaka/acc/AccCpuThreads.hpp
  alpaka/include/alpaka/acc/AccDevProps.hpp
  alpaka/include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  alpaka/include/alpaka/alpaka.hpp
  alpaka/include/alpaka/block/shared/dyn/BlockSharedMemDynAlignedAlloc.hpp
  alpaka/include/alpaka/block/shared/dyn/BlockSharedMemDynMember.hpp
  alpaka/include/alpaka/block/shared/st/BlockSharedMemStMasterSync.hpp
  alpaka/include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp
  alpaka/include/alpaka/core/AlignedAlloc.hpp
  alpaka/include/alpaka/intrinsic/IntrinsicCpu.hpp
  alpaka/include/alpaka/intrinsic/IntrinsicUniformCudaHipBuiltIn.hpp
  alpaka/include/alpaka/intrinsic/Traits.hpp
  alpaka/include/alpaka/mem/alloc/AllocCpuAligned.hpp
  alpaka/include/alpaka/mem/buf/BufCpu.hpp
  alpaka/include/alpaka/warp/WarpUniformCudaHipBuiltIn.hpp
  alpaka/script/after_failure.sh
  alpaka/script/before_install.sh
  alpaka/script/ci.sh
  alpaka/script/docker_install.sh
  alpaka/script/docker_run.sh
  alpaka/script/install.sh
  alpaka/script/install_analysis.sh
  alpaka/script/install_boost.sh
  alpaka/script/install_cmake.sh
  alpaka/script/install_cuda.sh
  alpaka/script/install_tbb.sh
  alpaka/script/print_env.sh
  alpaka/script/run.sh
  alpaka/script/run_analysis.sh
  alpaka/script/run_build.sh
  alpaka/script/run_generate.sh
  alpaka/script/run_tests.sh
  alpaka/test/unit/CMakeLists.txt
  alpaka/test/unit/acc/src/AccDevPropsTest.cpp
  alpaka/test/unit/intrinsic/src/Popcount.cpp
  alpaka/test/unit/workDiv/CMakeLists.txt
  alpaka/test/unit/workDiv/src/WorkDivHelpersTest.cpp
Labels: refactoring

#189 fix data race and printf issue
  examples/mallocMC_example03.cpp
Labels: bug

#190 fix data races in `Scatter.hpp`
  src/include/mallocMC/creationPolicies/Scatter.hpp
Labels: bug

#192 fix clang cuda compile
  src/include/mallocMC/creationPolicies/Scatter.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp
  src/include/mallocMC/mallocMC_utils.hpp
Labels: bug

#193 fix HIP-clang runtime issues
  src/include/mallocMC/allocator.hpp
Labels: bug
