Repository alpaka-group/mallocMC, pull requests merged in 2021-02, with the labels that each got.

#207 update changelog for 2.5.0crp
  CHANGELOG.md
Labels: documentation

#206 switch from rodare to zenodo
  .rodare.json
  .zenodo.json
Labels: documentation

#211 fix documentation
  INSTALL.md
  README.md
Labels: bug, documentation

#215 Add CI step to verify formatting
  .github/workflows/ci.yml
  examples/mallocMC_example01.cpp
  examples/mallocMC_example03.cpp
  src/include/mallocMC/creationPolicies/Scatter.hpp
  src/include/mallocMC/distributionPolicies/Noop.hpp
  src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp
  src/include/mallocMC/mallocMC_utils.hpp
  src/include/mallocMC/reservePoolPolicies/AlpakaBuf.hpp
  tests/verify_heap.cpp
Labels: example/test

#210 pull changes from release 2.5.0crp
  .zenodo.json
  CHANGELOG.md
  src/include/mallocMC/version.hpp
Labels: documentation

#216 fix clang format test
  .github/workflows/ci.yml
Labels: example/test

#213 add full support for CPU accelerators
  examples/mallocMC_example01.cpp
  examples/mallocMC_example03.cpp
  src/include/mallocMC/creationPolicies/Scatter.hpp
  tests/dimensions.cpp
  tests/verify_heap.cpp
  tests/verify_heap_config.hpp
Labels: refactoring
