Repository alpaka-group/mallocMC, pull requests merged in 2024-08, with the labels that each got.

#253 fix few bugs
  src/include/mallocMC/creationPolicies/Scatter.hpp
Labels: bug

#247 Fit `accessblocksize` into heap for examples and tests
  examples/mallocMC_example01.cpp
  examples/mallocMC_example03.cpp
  tests/dimensions.cpp
  tests/policies.cpp
Labels: bug, example/test

#258 Update alpaka version number in INSTALL.md
  INSTALL.md
Labels: documentation

#259 Fix wrong multi-page condition
  src/include/mallocMC/creationPolicies/Scatter.hpp
Labels: bug

#250 Make reservation policy owning
  src/include/mallocMC/allocator.hpp
  src/include/mallocMC/reservePoolPolicies/AlpakaBuf.hpp
  src/include/mallocMC/reservePoolPolicies/CudaSetLimits.hpp
Labels: refactoring

#261 Bump version to 3.0.0
  src/include/mallocMC/version.hpp
Labels: documentation

#260 Release 2.6.0
  .zenodo.json
  CHANGELOG.md
Labels: documentation
